apiVersion: v1
kind: ConfigMap
metadata:
  name: yunikorn-configs
  namespace: yunikorn
data:
  service.volumeBindTimeout: "60s"
  service.placeholderImage: "registry.k8s.io/pause:3.7"
  service.operatorPlugins: "general,spark-k8s-operator,spark"
  admissionController.filtering.bypassNamespaces: "^kube-system$,^karpenter$,^kube-prometheus-stack$"
  service.overcommitFactor: "1.5"
  service.enableDynamicQueueSizing: "true"
  service.enablePlaceholderPods: "true"
  service.gangSchedulingStyle: "Soft"

  queues.yaml: |
    partitions:
      - name: default
        nodesortpolicy:
          type: binpacking
        queues:
          - name: root
            submitacl: '*'
            queues:
              - name: default
                resources:
                  guaranteed:
                    memory: 4000G
                    vcore: 2000
                  max:
                    memory: 6000G
                    vcore: 3000
              - name: spark
                resources:
                  guaranteed:
                    memory: 6000G
                    vcore: 3000
                  max:
                    memory: 8000G
                    vcore: 5000
              - name: monitoring
                resources:
                  guaranteed:
                    memory: 600G
                    vcore: 3000
                  max:
                    memory: 800G
                    vcore: 5000
              - name: prod
                resources:
                  guaranteed:
                    memory: 500G
                    vcore: 50
                  max:
                    memory: 800G
                    vcore: 300
              - name: test
                resources:
                  guaranteed:
                    memory: 100G
                    vcore: 10
                  max:
                    memory: 800G
                    vcore: 50
              - name: dev
                resources:
                  guaranteed:
                    memory: 100G
                    vcore: 10
                  max:
                    memory: 100G
                    vcore: 10