apiVersion: v1
kind: ConfigMap
metadata:
  name: yunikorn-configs
  namespace: yunikorn
data:
  service.volumeBindTimeout: "60s"
  service.placeholderImage: "registry.k8s.io/pause:3.7"
  service.operatorPlugins: "general,spark-k8s-operator,spark"
  admissionController.filtering.bypassNamespaces: "^kube-system$"
  queues.yaml: |
    partitions:
      - name: default
        nodesortpolicy:
          type: binpacking
        queues:
          - name: root
            submitacl: '*'
            queues:
              - name: default
                resources:
                  guaranteed:
                    memory: 1000G
                    vcore: 1000
                  max:
                    memory: 1000G
                    vcore: 1000
              - name: prod
                resources:
                  guaranteed:
                    memory: 500G
                    vcore: 50
                  max:
                    memory: 800G
                    vcore: 300
              - name: test
                resources:
                  guaranteed:
                    memory: 100G
                    vcore: 10
                  max:
                    memory: 800G
                    vcore: 50
              - name: dev
                resources:
                  guaranteed:
                    memory: 100G
                    vcore: 10
                  max:
                    memory: 100G
                    vcore: 10