prometheus:
  serviceAccount:
    create: true
    name: ${amp_sa}
    annotations:
      eks.amazonaws.com/role-arn: ${amp_irsa}
  prometheusSpec:
    remoteWrite:
      - url: ${amp_remotewrite_url}
        sigv4:
          region: ${region}
        queueConfig:
          maxSamplesPerSend: 500
          maxShards: 200
          capacity: 2500
    retention: 4h
    scrapeInterval: 600s
    evaluationInterval: 600s
    scrapeTimeout: 50s
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: ${storage_class_type}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
    additionalScrapeConfigs:
      - job_name: kubecost
        honor_labels: true
        scrape_interval: 10m
        scrape_timeout: 30s
        metrics_path: /metrics
        scheme: http
        dns_sd_configs:
          - names:
              - kubecost-cost-analyzer.kubecost
            type: 'A'
            port: 9003

            ################
  serviceMonitor:
    enabled: true
#####################################
alertmanager:
  enabled: false

grafana:
  enabled: true
  defaultDashboardsEnabled: true
# Adding AMP datasource to Grafana config
  serviceAccount:
    create: false
    name: ${amp_sa}
  grafana.ini:
    auth:
      sigv4_auth_enabled: true
  additionalDataSources:
    - name: AMP
      editable: true
      jsonData:
        sigV4Auth: true
        sigV4Region: ${region}
      type: prometheus
      isDefault: false
      url: ${amp_url}

      #####################
prometheusRule:
  enabled: true

  #########################