apiVersion: v1
kind: ConfigMap
metadata:
  name: yunikorn-configs
  namespace: yunikorn
data:
  service.volumeBindTimeout: "60s"
  service.placeholderImage: "registry.k8s.io/pause:3.7"
  service.operatorPlugins: "general,spark-k8s-operator"
  admissionController.filtering.bypassNamespaces: "^kube-system$"